# Generated by Django 5.0.4 on 2024-04-11 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appartments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquirymodel',
            name='land',
        ),
        migrations.AlterField(
            model_name='apartmentmodel',
            name='photo_url',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(code='invalid_url', message='URL must start with "http://" or "https://"', regex='^https?://')]),
        ),
    ]
