# Generated by Django 5.0.4 on 2024-04-12 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appartments', '0002_remove_inquirymodel_land_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentmodel',
            name='name',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentmodel',
            name='photo_url',
            field=models.CharField(blank=True, max_length=2000, null=True, validators=[django.core.validators.RegexValidator(code='invalid_url', message='URL must start with "http://" or "https://"', regex='^https?://')]),
        ),
        migrations.AlterField(
            model_name='maintenancerequestmodel',
            name='apartment',
            field=models.TextField(),
        ),
    ]
