# Generated by Django 5.0.4 on 2024-04-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appartments', '0003_apartmentmodel_name_alter_apartmentmodel_photo_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquirymodel',
            name='user',
        ),
        migrations.AddField(
            model_name='inquirymodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
