# Generated by Django 5.0.4 on 2024-04-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appartments', '0004_remove_inquirymodel_user_inquirymodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='airbnbmodel',
            name='name',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
    ]
